### ISSUE TITLE
Representing table setting conditions.

### ISSUE THREAD

**Issue by Mome** [ease-crc/soma#199]
@mpomarlan
Table setting tasks in the EASE-TSD setup can have three conditions with the following values:

_meal\_type_ ∈ { _breakfast_, _lunch_, _dinner_ }
_formality_ ∈ { _formal_, _informal_ }
_number\_of\_persons_ ∈ ℕ

What is the best way to express this in SOMA ?

**Comment by mpomarlan** [comment]
I don't have a good answer for this yet, but we have a small meeting in the ontology task force tomorrow and we will put this on the agenda.

**Comment by mpomarlan** [comment]
After the discussion in the onto group, here's a summary:

1) since this metadata is useful to filter NEEMs, it would be good for it to be easily accessible, that is, a user shouldn't have to load the NEEM to get at it. So if you've so far placed this metadata in its own file, keep doing so. It is a practical solution to a need.

2) we will have the metadata attached to an episode individual inside the NEEM as well. This will not make the metadata file obsolete -- as I said, it seems useful to have the metadata easily available -- rather it is intended to remove an incompleteness from the NEEM itself.

I will keep the issue open until we push the relevant concepts for point 2) into SOMA.

**Comment by Mome** [comment]
1. Ok, I'll keep all the meta data inside NeemHub then as well

2. Here it depends on what you consider meta-data. So this like fielpath, filesize, filetype, etc is information that does not necessarily need to be stored in the NEEMs.
Regarding information about what modalities (video,  EEG,  etc) were recorded: This more important since potential users are more likely to query for that.
Regarding the original question of the inclusion of task conditions.  I would not consider them as meta-data (from my non-informed intuition), since they are not file-related but rather properties of tasks.
