### ISSUE TITLE
States, qualities and regions

### ISSUE THREAD

**Issue by daniel86** [ease-crc/soma#7]
- how do they relate to each other?
- how to represent change over time?
- how to represent quantitative time-varying data such as pose?
- 4D, reification, or no explicit temporal representation (in OWL) at all?
- how would 4D work together with DUL?

**Comment by mpomarlan** [comment]
This probably needs to be split into several issues. Change over time, and in particular the 4D/reification decisions, should be its own thing(s), separate from the relationship between states, qualities, and regions.

Separating this into more issues will also, maybe, help document the various discussions we had in the Monday meetings, for example about fluents and what kinds of inference they allow, as opposed to a purely State/temporal part representation. It would also help clarify what the issues actually are. I don't know what the issue is of using 4D with DUL. I'm sure there is one, but it's better to formulate it in the github issue text so we all know what we're talking about.

**Comment by daniel86** [comment]
Yes, I agree. Does not seem that github has a nice interface for "composite tickets". Anyway we can keep this ticket + create more fine grained ones, then just referring to each other within the tickets.

@mpomarlan do you have a suggestion how we should split this up?

**Comment by daniel86** [comment]
*temporal representations* let's discuss this again then. Generally much of the time-varying data should probably not be explicated symbolically at all. Or at least only as quality and not as data values. Maybe I should move away from this "could be symbolically represented or stored in a DB collection".
But representations are not the only aspect here, most important is how reasoning is performed with these representations. I liked the rather "hackish" approach of having all facts holding at the current time asserted without 4D or reification such that non temporal reasoner was able to deduce the "current state" -- anyway John's reaction was not very positive when I tried to explain :)

Finally, I tried to use temporal representations in rules. But it proofed to be rather unintuitive to write such rules, and I felt better writing rules with *implicit time quantification*. Because it was too much of a hassle to explicate temporal semantics. Thus, our temporal representation should fit nicely with some rule language that allows us to qualify what changes over time using rules.

The distinction between qualities/regions is very useful. Regions are data values which are usually easier recognizable by the robot then qualities. In many cases the quality could be seen as a symbolic abstraction of data we store in mongo / that was perceived by the robot.

**Comment by daniel86** [comment]
Well *Hot* would rather be a region again then a value. But a highly ambiguous one,
because being *Hot* means something different for the *Water* when I intend to cook it compared to when I want to drink it, for example.
You can also see it as more specific quality then "having a temperature", namely "having a high temperature".

I was thinking that qualities and regions are in particular meant for separating the vague natural language expressions referring to quality from the rather measured world of particular values.
