### ISSUE TITLE
Transient/Transition pattern

### ISSUE THREAD

**Issue by daniel86** [ease-crc/soma#8]
*A pattern to deal with processes that transform objects such as a *Baking* process transforming a (disc shaped) blob of dough into an edible pancake (and that allows to specify phases of the transformation?).*

**Def Transient**

*Objects may undergo changes during Processes; however, while the change Process is in operation, one cannot strictly say either the input of the Process still exists, nor that the result exists yet.
A prototypical example is making a pancake on a heater. When PancakeMix is put on the hot plate, it ceases to be PancakeMix-- already, the chemical structure of the substance gets altered-- however it is only after sufficient heating that this object becomes a Pancake.
Transients are the objects undergoing such change processes; they are no longer the initial objects fed into the process, nor are they the objects produced as results.
Instead, a Transient transitionsFrom some initial Object that was fed into a change Process. Typically, a Transient may transitionTo some resulting Object (though not always, some processes simply destroy objects).
It is also possible that a Transient transitionsBack to the initial object. An example is the catalyst in a chemical reaction; another example is a loaf of bread after a slice has been cut off.*

**Comment by daniel86** [comment]
Exisitng proposal is here:
  http://ontologydesignpatterns.org/wiki/Submissions:Transition

**Comment by daniel86** [comment]
For discussion: How should tasks be axiomatized? The problem is that the *Transient* is participant in the action, and plays some role defined in the task that is executed (that might be *AlteredObject*). But the transition from/to also play a roles during the action (*Commited* and *Created*). Again, co-reference can not be expressed, so either we ignore this ambiguity, would only use the *AlteredObject* role for the transient or only the *Commited* and *Created* roles to imply that there is a transient.

**Comment by daniel86** [comment]
For discussion: How are relations to other entities derived from input to output of a transient? for example a pancake created by baking dough still contains the same ingredients, however, potentially also in a changed form. But still one would say that the pancake "contains flour".
Also, how are qualities derived?

**Comment by daniel86** [comment]
> For discussion: How are relations to other entities derived from input to output of a transient? for example a pancake created by baking dough still contains the same ingredients, however, potentially also in a changed form. But still one would say that the pancake "contains flour".
> Also, how are qualities derived?

simple solution: relations are derived in case the related object still exists. But not sure if this is always the case, maybe only for some relations?

**Comment by daniel86** [comment]
> For discussion: How should tasks be axiomatized? The problem is that the _Transient_ is participant in the action, and plays some role defined in the task that is executed (that might be _AlteredObject_). But the transition from/to objects also play roles during the action (_Commited_ and _Created_). Again, co-reference can not be expressed, so either we ignore this ambiguity, we only use the _AlteredObject_ role for the transient, or only the _Commited_ and _Created_ roles to imply that there is a transient.
> All seems non-optimal.

Here is a proposal: The definition of a task does not include a role for the transient. However, within plans one might specify that a step of a plan has a phase which is a transition (process). Then we can use the (workflow) role bindings to imply the identity constraints between fillers of roles of the transition and the action.

**Comment by daniel86** [comment]
For discussion: How is the transient classified? e.g. is the Dough-Pancake transient both Dough and Pancake or non of it?
I assume we want it to be both, such that we can refer to it using both types.
Can this be axiomatized?

**Comment by mpomarlan** [comment]
Task axiomatization:

I agree with leaving the transient out of the task definition. If we have to sacrifice something, I'd sacrifice the transient, the intuition being that a definition of a task should make it easy to access pre- and post-conditions of the corresponding action. We can incorporate the details of how a task is to be performed elsewhere.

**Comment by mpomarlan** [comment]
Relations between transient and to-, from- entities:

I'm not sure that some abstract, general purpose treatment will work here. We need to look at some examples. The reason I say this is because constituency/parthood relations need not be preserved by the operation that manipulates the transient. In particular, chemical composition often changes during cooking operations, and physical transformations that destroy structure also destroy parts of the input objects.

Of course, natural language often works in very non-rigorous ways. Someone might refuse to eat red candy because "there's bugs in it". There are no bugs in the candy, from a strict parthood perspective; however it is true that the red pigment was obtained from ground up wing covers of the cochineal beetle. I would suggest we however place the complexity of interpreting a natural language query on the side of a parser, rather than the ontology.

As in, rather than have a parthood relation that can link candy to beetles because pigments from the beetles were used in the candy, I'd have a parser that can pose several candidate interpretations for a question such as "are there any bugs in this candy". One interpretation in terms of parthood, one interpretation in terms of two entities separated by time sharing the same substance, etc.

**Comment by mpomarlan** [comment]
Transient classification:

My impression was, a transient is neither Dough nor Pancake.

This has again to do with language and its vagaries. If someone asked a robot "where is the dough" (or "where is the pancake"), the robot can reasonably point to the pan where the thing is being fried. But this is not because the thing on the pan is still a piece of dough, or has become a complete pancake. Rather, it's because we're very malleable in how we use words.

The way to see this, I think, is that if the person asked "bring me the dough", they would not be happy with the robot bringing them a half-baked pancake. That "dough" no longer offers the dispositions that dough offers, such as shapeability into new forms nor the same ease to mix in new ingredients.

So, much like in the case of the "relations between transient and to-, from- entities" answer, I would suggest this to be kicked down to the parser, rather than the ontological model. Ie., have the parser suggest several interpretations for a question such as "where is the dough", among them

-- is there an entity of type dough and if so where
-- is there an entity produced out of something that was of type dough and if so where

This btw. suggests the possibility of a very nice COLING or EKAW paper :)

**Comment by daniel86** [comment]
> Transient classification:
> 
> My impression was, a transient is neither Dough nor Pancake.
> 
> This has again to do with language and its vagaries. If someone asked a robot "where is the dough" (or "where is the pancake"), the robot can reasonably point to the pan where the thing is being fried. But this is not because the thing on the pan is still a piece of dough, or has become a complete pancake. Rather, it's because we're very malleable in how we use words.
> 
> The way to see this, I think, is that if the person asked "bring me the dough", they would not be happy with the robot bringing them a half-baked pancake. That "dough" no longer offers the dispositions that dough offers, such as shapeability into new forms nor the same ease to mix in new ingredients.
> 
> So, much like in the case of the "relations between transient and to-, from- entities" answer, I would suggest this to be kicked down to the parser, rather than the ontological model. Ie., have the parser suggest several interpretations for a question such as "where is the dough", among them
> 
> -- is there an entity of type dough and if so where
> -- is there an entity produced out of something that was of type dough and if so where
> 
> This btw. suggests the possibility of a very nice COLING or EKAW paper :)

Yes, I agree. I think a cool story could be to generate the grammar for the parser, by e.g. path finding in the ontology graph together with some additional knowledge to constrain the parser generation a bit (e.g. traverse only along certain categories of relations).

We could also list, e.g., objects that could be used to create a pancake, or objects that can be used with a dough such as the fridge that may contain some
